Allow to set the participations for a PartialEvent
Calendart/GoogleAdapter pull request #14
Opened 2016-10-17 15:50 UTC by krichprollsch

The ability to set the participations could be need for example if we want to remove all the participations and force the export to show it.

2016-10-17 16:27 UTC, Taluu requested changes
Not a fan to reset the whole collection, but meh I see the use cases

2016-10-17 16:27 UTC, Taluu commented on src/Event/PartialEvent.php
> +    {
control what is in the collection, as you could have a collection of `string` for example.

2016-10-17 16:27 UTC, Taluu commented on src/Event/PartialEvent.php
> +    {
And also, you should use the `Collection` type instead, instead of `ArrayCollection`

2016-10-18 09:19 UTC, krichprollsch commented
@Taluu ty for your review, I just update the PR.

2016-10-18 10:03 UTC, Taluu requested changes

2016-10-18 10:03 UTC, Taluu commented on src/Event/PartialEvent.php
> +                throw new InvalidArgumentException(sprintf('All participations must be instance of %s', BaseEventParticipation::class));
Oops, not php 5.4. But maybe we should bump the requirement...

2016-10-18 10:58 UTC, krichprollsch commented
changed @Taluu

2016-10-18 11:33 UTC, Taluu approved these changes

2016-10-18 11:33 UTC, Taluu commented
LGTM 👍

2016-10-18 11:33 UTC, merged